<?php

namespace Tests\Feature;

use App\Enums\CallOutcome;
use App\Filament\Pages\MainDashboard;
use App\Filament\Pages\MyDashboard;
use App\Filament\Widgets\DashboardGreeting;
use App\Models\CallRecord;
use App\Models\Prospect;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Date;
use Livewire\Livewire;
use Tests\TestCase;

/**
 * The dashboard's personalized greeting (opening date line/"Good
 * morning/afternoon/evening, {name}"/subtitle), added to both Main
 * Dashboard and My Dashboard. Time-of-day is read from Date::now(), which
 * respects config('app.timezone') (Asia/Kolkata) — not raw UTC — matching
 * "based on server time" as requested. The subtitle's call count is
 * exactly App\Filament\Widgets\KpiBand's own "Calls" tile query
 * (CallRecord::query(), scoped/filtered the same way), not a new metric
 * invented for this widget.
 */
class DashboardGreetingTest extends TestCase
{
    use RefreshDatabase;

    protected function tearDown(): void
    {
        Date::setTestNow();

        parent::tearDown();
    }

    public function test_greeting_says_good_morning_before_noon(): void
    {
        Date::setTestNow(Date::parse('2026-01-01 09:00:00'));
        $this->actingAs(User::factory()->create(['name' => 'Priya Sharma']));

        $greeting = Livewire::test(DashboardGreeting::class)->instance()->getGreeting();

        $this->assertSame('Good morning, Priya', $greeting);
    }

    public function test_greeting_says_good_afternoon_between_noon_and_six(): void
    {
        Date::setTestNow(Date::parse('2026-01-01 14:00:00'));
        $this->actingAs(User::factory()->create(['name' => 'Priya Sharma']));

        $greeting = Livewire::test(DashboardGreeting::class)->instance()->getGreeting();

        $this->assertSame('Good afternoon, Priya', $greeting);
    }

    public function test_greeting_says_good_evening_after_six(): void
    {
        Date::setTestNow(Date::parse('2026-01-01 20:00:00'));
        $this->actingAs(User::factory()->create(['name' => 'Priya Sharma']));

        $greeting = Livewire::test(DashboardGreeting::class)->instance()->getGreeting();

        $this->assertSame('Good evening, Priya', $greeting);
    }

    public function test_date_line_matches_the_current_date(): void
    {
        Date::setTestNow(Date::parse('2026-08-25 10:00:00'));
        $this->actingAs(User::factory()->create());

        $dateLine = Livewire::test(DashboardGreeting::class)->instance()->getDateLine();

        $this->assertSame('Tuesday · 25 August', $dateLine);
    }

    public function test_subtitle_reflects_the_real_directly_logged_call_count_company_wide(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);

        $prospect = Prospect::factory()->create(['assigned_to' => $user->id, 'created_by' => $user->id]);
        CallRecord::create(['prospect_id' => $prospect->id, 'user_id' => $user->id, 'called_at' => now(), 'outcome' => CallOutcome::NoAnswer]);
        CallRecord::create(['prospect_id' => $prospect->id, 'user_id' => $user->id, 'called_at' => now(), 'outcome' => CallOutcome::NoAnswer]);

        $subtitle = Livewire::test(DashboardGreeting::class, ['employeeId' => null])->instance()->getSubtitle();

        $this->assertSame("Your team has logged 2 calls this cycle.", $subtitle);
    }

    public function test_subtitle_is_personal_when_scoped_to_an_employee(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);

        $prospect = Prospect::factory()->create(['assigned_to' => $user->id, 'created_by' => $user->id]);
        CallRecord::create(['prospect_id' => $prospect->id, 'user_id' => $user->id, 'called_at' => now(), 'outcome' => CallOutcome::NoAnswer]);

        $subtitle = Livewire::test(DashboardGreeting::class, ['employeeId' => $user->id])->instance()->getSubtitle();

        $this->assertSame("You've logged 1 call this cycle.", $subtitle);
    }

    /**
     * A Call Record generated by completing a Follow-Up is no longer
     * hidden anywhere (an earlier version of this feature excluded it from
     * this exact subtitle count via a now-removed directlyLogged() call —
     * see FollowUpGeneratedCallRecordVisibilityTest for the full revert),
     * so it counts here exactly like a directly-logged call.
     */
    public function test_subtitle_counts_a_call_record_generated_by_completing_a_follow_up(): void
    {
        $user = User::factory()->create();
        $this->actingAs($user);

        $prospect = Prospect::factory()->create(['assigned_to' => $user->id, 'created_by' => $user->id]);
        $directCall = CallRecord::create(['prospect_id' => $prospect->id, 'user_id' => $user->id, 'called_at' => now(), 'outcome' => CallOutcome::NoAnswer]);

        CallRecord::create([
            'prospect_id' => $prospect->id,
            'user_id' => $user->id,
            'called_at' => now(),
            'outcome' => CallOutcome::NoAnswer,
            'follow_up_id' => $directCall->fresh()->followUp->id,
        ]);

        $subtitle = Livewire::test(DashboardGreeting::class, ['employeeId' => null])->instance()->getSubtitle();

        $this->assertSame("Your team has logged 2 calls this cycle.", $subtitle);
    }

    public function test_both_dashboards_register_the_greeting_widget(): void
    {
        $this->assertContains(DashboardGreeting::class, (new MainDashboard)->getWidgets());
        $this->assertContains(DashboardGreeting::class, (new MyDashboard)->getWidgets());
    }

    /**
     * Bug fix (follow-up request): the plain "Main Dashboard"/"My
     * Dashboard" page heading sat directly above DashboardGreeting's own
     * "Good morning, {name}" — redundant, since the greeting now serves
     * as the page's heading. Suppressing getHeading() (not getTitle(),
     * which still drives the browser tab's <title>) removes it —
     * vendor/filament/filament/resources/views/components/page/index.
     * blade.php only renders the header block at all when
     * `$this->getHeading()` is truthy.
     */
    public function test_both_dashboards_suppress_the_plain_page_heading(): void
    {
        $this->assertSame('', (new MainDashboard)->getHeading());
        $this->assertSame('', (new MyDashboard)->getHeading());
    }

    public function test_both_dashboards_keep_their_browser_tab_title(): void
    {
        $this->assertSame('Main Dashboard', (new MainDashboard)->getTitle());
        $this->assertSame('My Dashboard', (new MyDashboard)->getTitle());
    }
}
