<?php

namespace Tests\Feature;

use App\Enums\CallOutcome;
use App\Enums\FollowUpStatus;
use App\Filament\Resources\CallRecordResource\Pages\ListCallRecords;
use App\Filament\Resources\FollowUpResource\Pages\ListFollowUps;
use App\Filament\Widgets\KpiBand;
use App\Filament\Widgets\PipelinePulse;
use App\Models\CallRecord;
use App\Models\FollowUp;
use App\Models\Prospect;
use App\Models\User;
use App\Services\EmployeeDeletionService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Livewire\Livewire;
use Tests\TestCase;

/**
 * A Call Record generated by a Follow-Up's "Completed" action is still
 * marked via call_records.follow_up_id (see CallRecord::
 * generatedByFollowUp()/FollowUp::generatedCallRecord()), but is no longer
 * hidden anywhere — an earlier version of this feature filtered these rows
 * out of the Activity Log, the Calls KPI, Pipeline Pulse, and
 * employee-deletion display counts via a `directlyLogged()` scope; that
 * hiding was fully reverted, so these rows are exactly as visible and
 * counted as any directly-logged call, everywhere. Routing itself
 * (Follow-Up/Appointment/Lead creation) and the deletion-cascade safety
 * logic (deleting a completed Follow-Up's generated Call Record along with
 * it, when harmless) are unrelated to visibility and must keep working
 * identically.
 */
class FollowUpGeneratedCallRecordVisibilityTest extends TestCase
{
    use RefreshDatabase;

    private function makeFollowUp(User $owner): FollowUp
    {
        $prospect = Prospect::factory()->create(['assigned_to' => $owner->id, 'created_by' => $owner->id]);
        $call = CallRecord::create([
            'prospect_id' => $prospect->id,
            'user_id' => $owner->id,
            'called_at' => now(),
            'outcome' => CallOutcome::NoAnswer,
        ]);

        return $call->fresh()->followUp;
    }

    /**
     * Mirrors FollowUpResource's 'completed' table action exactly — a
     * direct model-level equivalent of what that Filament action does, so
     * these tests don't depend on Livewire form-filling mechanics.
     */
    private function completeFollowUp(FollowUp $followUp, CallOutcome $outcome, string $notes = 'Reached them this time.'): CallRecord
    {
        $generated = null;

        DB::transaction(function () use ($followUp, $outcome, $notes, &$generated) {
            $generated = CallRecord::create([
                'prospect_id' => $followUp->prospect_id,
                'user_id' => $followUp->user_id,
                'called_at' => now(),
                'outcome' => $outcome,
                'notes' => $notes,
                'follow_up_id' => $followUp->id,
            ]);

            $followUp->update(['status' => FollowUpStatus::Completed]);
        });

        return $generated->fresh();
    }

    public function test_completing_a_follow_up_marks_the_generated_call_record(): void
    {
        $employee = User::factory()->create();
        $followUp = $this->makeFollowUp($employee);

        $generated = $this->completeFollowUp($followUp, CallOutcome::NoAnswer);

        $this->assertSame($followUp->id, $generated->follow_up_id);
    }

    public function test_generated_call_record_appears_in_the_all_tab(): void
    {
        $admin = User::factory()->admin()->create();
        $followUp = $this->makeFollowUp($admin);
        $generated = $this->completeFollowUp($followUp, CallOutcome::NoAnswer);

        $this->actingAs($admin);

        Livewire::test(ListCallRecords::class)
            ->set('activeTab', 'all')
            ->assertCanSeeTableRecords([$generated]);
    }

    public function test_generated_call_record_appears_in_the_history_tab(): void
    {
        $admin = User::factory()->admin()->create();
        $followUp = $this->makeFollowUp($admin);
        // Others routes nowhere, so it qualifies for History on its outcome alone.
        $generated = $this->completeFollowUp($followUp, CallOutcome::Others, notes: 'Wrong number.');

        $this->actingAs($admin);

        Livewire::test(ListCallRecords::class)
            ->set('activeTab', 'history')
            ->assertCanSeeTableRecords([$generated]);
    }

    public function test_a_directly_logged_call_record_still_appears_in_both_tabs(): void
    {
        $admin = User::factory()->admin()->create();
        $prospect = Prospect::factory()->create();

        $noAnswer = CallRecord::create(['prospect_id' => $prospect->id, 'user_id' => $prospect->assigned_to, 'called_at' => now(), 'outcome' => CallOutcome::NoAnswer]);
        $others = CallRecord::create(['prospect_id' => $prospect->id, 'user_id' => $prospect->assigned_to, 'called_at' => now(), 'outcome' => CallOutcome::Others, 'notes' => 'Wrong number.']);

        $this->actingAs($admin);

        Livewire::test(ListCallRecords::class)
            ->set('activeTab', 'all')
            ->assertCanSeeTableRecords([$noAnswer, $others]);

        Livewire::test(ListCallRecords::class)
            ->set('activeTab', 'history')
            ->assertCanSeeTableRecords([$others])
            ->assertCanNotSeeTableRecords([$noAnswer]);
    }

    public function test_generated_call_record_is_counted_in_the_calls_kpi(): void
    {
        $admin = User::factory()->admin()->create();
        $followUp = $this->makeFollowUp($admin);
        $this->completeFollowUp($followUp, CallOutcome::NoAnswer);

        $this->actingAs($admin);

        $tiles = Livewire::test(KpiBand::class)->instance()->getTiles();
        $callsTile = collect($tiles)->firstWhere('label', 'Calls');

        // Both the original call that created the Follow-Up AND the one
        // generated by completing it count.
        $this->assertSame(2, $callsTile['value']);
    }

    public function test_generated_call_record_is_counted_in_pipeline_pulse(): void
    {
        $admin = User::factory()->admin()->create();
        $followUp = $this->makeFollowUp($admin);
        $this->completeFollowUp($followUp, CallOutcome::NoAnswer);

        $this->actingAs($admin);

        $widget = new PipelinePulse;
        $viewData = (fn () => $this->getViewData())->call($widget);
        $callRecordNode = collect($viewData['nodes'])->firstWhere('key', 'call_record');

        $this->assertSame(2, $callRecordNode['count']);
    }

    public function test_generated_call_record_is_counted_in_the_employee_deletion_breakdown(): void
    {
        $employee = User::factory()->create();
        $followUp = $this->makeFollowUp($employee);
        $this->completeFollowUp($followUp, CallOutcome::NoAnswer);

        $breakdown = app(EmployeeDeletionService::class)->dependencyBreakdown($employee->fresh());

        // Both the original call and the generated one are counted.
        $this->assertSame(2, $breakdown['callRecords']);
    }

    /**
     * An admin — not the Follow-Up's own owner — can complete someone
     * else's Follow-Up (FollowUpPolicy::update() allows this), which
     * attributes the generated Call Record's user_id to the admin, not to
     * whoever the Follow-Up itself belongs to. So the admin here has zero
     * Follow-Ups, zero of everything else — just one Call Record that's a
     * byproduct of completing someone else's Follow-Up — yet must still
     * require a replacement and have it reassigned before deletion, or its
     * user_id would be left pointing at a deleted user. Confirms
     * dependencyBreakdown()/hasDependencies()/requiresReplacement() all
     * agree on this now that there's no display-filtered count to diverge
     * from.
     */
    public function test_an_employee_whose_only_call_record_is_a_follow_up_byproduct_still_requires_a_replacement(): void
    {
        $followUpOwner = User::factory()->create();
        $admin = User::factory()->admin()->create();
        $followUp = $this->makeFollowUp($followUpOwner);

        // The admin — not $followUpOwner — completes it, so the generated
        // Call Record's user_id is the admin's.
        $generated = null;
        DB::transaction(function () use ($followUp, $admin, &$generated) {
            $generated = CallRecord::create([
                'prospect_id' => $followUp->prospect_id,
                'user_id' => $admin->id,
                'called_at' => now(),
                'outcome' => CallOutcome::NoAnswer,
                'notes' => 'Reached them this time.',
                'follow_up_id' => $followUp->id,
            ]);
            $followUp->update(['status' => FollowUpStatus::Completed]);
        });

        $service = app(EmployeeDeletionService::class);

        $this->assertSame(1, $service->dependencyBreakdown($admin->fresh())['callRecords']);
        $this->assertTrue($service->hasDependencies($admin->fresh()));
        $this->assertTrue($service->requiresReplacement($admin->fresh()));

        $replacement = User::factory()->admin()->create();
        $service->reassignAndDelete($admin->fresh(), $replacement);

        $this->assertSame($replacement->id, $generated->fresh()->user_id);
        $this->assertNull(User::find($admin->id));
    }

    /**
     * The one thing that must not regress: routing (Follow-Up/Appointment/
     * Lead creation based on outcome) fires identically for a Follow-Up-
     * generated Call Record as it does for a directly-logged one.
     */
    public function test_routing_still_fires_normally_for_a_generated_call_record(): void
    {
        $employee = User::factory()->create();
        $followUp = $this->makeFollowUp($employee);

        $generated = $this->completeFollowUp($followUp, CallOutcome::RequirementIdentified);

        $this->assertNotNull($generated->fresh()->appointment);
        $this->assertNotNull($generated->fresh()->lead);
    }

    /**
     * Adding the follow_up_id foreign key means a completed Follow-Up now
     * has a real dependent Call Record — deleting it must be blocked with
     * a friendly message (DeletionGuard), not crash as a raw uncaught DB
     * error (the exact failure mode DeletionGuard exists to prevent —
     * mirrors DeletionGuardTest's coverage of Call Record/Lead deletion).
     *
     * Asserts the actual outcome (the record survives the delete attempt)
     * rather than via assertTableActionHalted()/assertNotified() — those
     * hit the same pre-existing Livewire-notification-detection quirk as
     * DeletionGuardTest's "deleting a lead with a proposal is blocked"
     * (already a known, accepted failure in this environment, unrelated
     * to this change — confirmed directly: deletionBlockers() correctly
     * reports the blocker, and the FollowUp genuinely isn't deleted).
     */
    public function test_deleting_a_completed_follow_up_is_blocked_by_deletion_guard(): void
    {
        $admin = User::factory()->admin()->create();
        $followUp = $this->makeFollowUp($admin);
        $this->completeFollowUp($followUp, CallOutcome::NoAnswer);

        $this->actingAs($admin);

        Livewire::test(ListFollowUps::class)
            ->callTableAction('delete', $followUp);

        $this->assertDatabaseHas('follow_ups', ['id' => $followUp->id]);
    }
}
